### ISSUE TITLE
want a news api

### ISSUE THREAD

**Issue by SourabhKanade** [SourabhKanade/react-news-app#2]
I have used newsapi.org for rendering news on console, its developer version is limited till localhost, So I want another GOOD API that can be rendered when deployed to Netlify.

**Comment by sagarchoudhary96** [comment]
can try using: https://mediastack.com/documentation

**Comment by SourabhKanade** [comment]
Of course but make sure all parameters work correctly.

**Comment by sagarchoudhary96** [comment]
i was just giving suggestion on what can be used, i won't be able to make PR for the same at the moment @SourabhKanade :)

**Comment by SourabhKanade** [comment]
Okay
